"""GitHub operations — create repo and push code.

Auth: uses GITHUB_TOKEN env var (or GH_TOKEN). The gh CLI and git push
both respect this token.  Each user sets their own token → repos are
created under their own account.
"""

import json
import os
import subprocess
from pathlib import Path

from strands import tool


def _get_github_token() -> str | None:
    """Resolve GitHub token from env vars or .env file."""
    for name in ("GITHUB_TOKEN", "GH_TOKEN"):
        val = os.environ.get(name)
        if val:
            return val
    try:
        from src.config import get_api_key
        return get_api_key("GITHUB_TOKEN")
    except (ImportError, KeyError):
        pass
    return None


@tool
def github_create_and_push(
    repo_name: str,
    local_path: str,
    description: str = "Generated by Design Agent",
    private: bool = False,
) -> str:
    """Create a public GitHub repository and push local project code to it.

    Uses the GitHub CLI (gh). The repo is created under the authenticated user's account.
    Repos are public by default so the deployed site's source code is shareable.

    Args:
        repo_name: Repository name (e.g. 'my-sales-dashboard').
        local_path: Absolute path to the local project directory to push.
        description: Repository description.
        private: Whether the repo should be private (default False — public).

    Returns:
        JSON with repo_url and push status.
    """
    project = Path(local_path)
    if not project.exists():
        return json.dumps({"error": f"Path does not exist: {local_path}"})

    visibility = "--private" if private else "--public"
    create_result = subprocess.run(
        ["gh", "repo", "create", repo_name, visibility, "--description", description, "--source", str(project), "--push"],
        capture_output=True,
        text=True,
        timeout=120,
    )

    if create_result.returncode != 0:
        if "already exists" in create_result.stderr:
            return _push_to_existing(repo_name, project)
        return json.dumps({"error": "gh repo create failed", "stderr": create_result.stderr[:500]})

    repo_url = create_result.stdout.strip()
    if not repo_url.startswith("http"):
        repo_url_result = subprocess.run(
            ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        repo_url = repo_url_result.stdout.strip()

    return json.dumps({
        "repo_url": repo_url,
        "repo_name": repo_name,
        "push_status": "success",
    })


def _push_to_existing(repo_name: str, project: Path) -> str:
    repo_url_result = subprocess.run(
        ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    repo_url = repo_url_result.stdout.strip()

    token = _get_github_token()
    push_url = repo_url
    if token and push_url.startswith("https://"):
        push_url = push_url.replace("https://", f"https://x-access-token:{token}@")

    git_env = {
        "GIT_AUTHOR_NAME": "Design Agent",
        "GIT_AUTHOR_EMAIL": "design-agent@local",
        "GIT_COMMITTER_NAME": "Design Agent",
        "GIT_COMMITTER_EMAIL": "design-agent@local",
        "PATH": os.environ.get("PATH", "/usr/bin:/usr/local/bin"),
    }
    if token:
        git_env["GITHUB_TOKEN"] = token
        git_env["GH_TOKEN"] = token

    subprocess.run(["git", "init"], cwd=project, capture_output=True, timeout=30)
    subprocess.run(["git", "add", "."], cwd=project, capture_output=True, timeout=30)
    subprocess.run(
        ["git", "commit", "-m", "Update from Design Agent"],
        cwd=project, capture_output=True, timeout=30, env=git_env,
    )
    subprocess.run(
        ["git", "remote", "add", "origin", push_url],
        cwd=project, capture_output=True, timeout=30,
    )
    push_result = subprocess.run(
        ["git", "push", "-u", "origin", "main", "--force"],
        cwd=project, capture_output=True, text=True, timeout=60, env=git_env,
    )

    if push_result.returncode != 0:
        return json.dumps({"error": "git push failed", "stderr": push_result.stderr[:500]})

    return json.dumps({
        "repo_url": repo_url,
        "repo_name": repo_name,
        "push_status": "success (force-pushed to existing)",
    })
