"""GitHub operations — create repo and push code.

Auth: uses GITHUB_TOKEN / GH_TOKEN env var. The gh CLI and git push
both respect this token. Each user sets their own token so repos are
created under their own account.
"""

import json
import os
import subprocess
from pathlib import Path

from strands import tool

from src.tools._validate import _redact_stderr, safe_project_name


def _get_github_token() -> str | None:
    for name in ("GITHUB_TOKEN", "GH_TOKEN"):
        val = os.environ.get(name)
        if val:
            return val
    try:
        from src.config import get_api_key
        return get_api_key("GITHUB_TOKEN")
    except (ImportError, KeyError):
        pass
    return None


def _ensure_git_repo(project: Path) -> None:
    git_dir = project / ".git"
    if git_dir.exists():
        return

    git_env = _git_env()
    subprocess.run(["git", "init", "-b", "main"], cwd=project, capture_output=True, timeout=30, check=True)
    subprocess.run(["git", "add", "."], cwd=project, capture_output=True, timeout=30, check=True)
    subprocess.run(
        ["git", "commit", "-m", "Initial commit from Design Agent"],
        cwd=project, capture_output=True, timeout=30, env=git_env, check=True,
    )


def _git_env() -> dict[str, str]:
    env = {
        "GIT_AUTHOR_NAME": "Design Agent",
        "GIT_AUTHOR_EMAIL": "design-agent@local",
        "GIT_COMMITTER_NAME": "Design Agent",
        "GIT_COMMITTER_EMAIL": "design-agent@local",
        "PATH": os.environ.get("PATH", "/usr/bin:/usr/local/bin"),
    }
    token = _get_github_token()
    if token:
        env["GITHUB_TOKEN"] = token
        env["GH_TOKEN"] = token
    return env


@tool
def github_create_and_push(
    repo_name: str,
    local_path: str,
    description: str = "Generated by Design Agent",
    private: bool = False,
) -> str:
    """Create a public GitHub repository and push local project code to it.

    Uses the GitHub CLI (gh). The repo is created under the authenticated user's account.
    Repos are public by default so the deployed site's source code is shareable.

    Args:
        repo_name: Repository name (e.g. 'my-sales-dashboard').
        local_path: Absolute path to the local project directory to push.
        description: Repository description.
        private: Whether the repo should be private (default False — public).

    Returns:
        JSON with repo_url and push status.
    """
    try:
        safe_project_name(repo_name)
    except ValueError as e:
        return json.dumps({"error": str(e)})

    project = Path(local_path)
    if not project.exists():
        return json.dumps({"error": f"Path does not exist: {local_path}"})

    _ensure_git_repo(project)

    visibility = "--private" if private else "--public"
    create_result = subprocess.run(
        ["gh", "repo", "create", repo_name, visibility, "--description", description, "--source", str(project), "--push"],
        capture_output=True,
        text=True,
        timeout=120,
    )

    if create_result.returncode != 0:
        if "already exists" in create_result.stderr:
            return _push_to_existing(repo_name, project)
        return json.dumps({"error": "gh repo create failed", "stderr": _redact_stderr(create_result.stderr)})

    repo_url = create_result.stdout.strip().split("\n")[0]
    if not repo_url.startswith("http"):
        repo_url = _get_repo_url(repo_name)

    return json.dumps({
        "repo_url": repo_url,
        "repo_name": repo_name,
        "push_status": "success",
    })


def _get_repo_url(repo_name: str) -> str:
    result = subprocess.run(
        ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    return result.stdout.strip()


def _push_to_existing(repo_name: str, project: Path) -> str:
    repo_url = _get_repo_url(repo_name)
    git_env = _git_env()

    subprocess.run(["git", "init", "-b", "main"], cwd=project, capture_output=True, timeout=30)
    subprocess.run(["git", "add", "."], cwd=project, capture_output=True, timeout=30)
    subprocess.run(
        ["git", "commit", "-m", "Update from Design Agent"],
        cwd=project, capture_output=True, timeout=30, env=git_env,
    )
    subprocess.run(
        ["git", "remote", "add", "origin", repo_url],
        cwd=project, capture_output=True, timeout=30,
    )
    push_result = subprocess.run(
        ["git", "push", "-u", "origin", "main", "--force"],
        cwd=project, capture_output=True, text=True, timeout=60, env=git_env,
    )

    if push_result.returncode != 0:
        return json.dumps({"error": "git push failed", "stderr": _redact_stderr(push_result.stderr)})

    return json.dumps({
        "repo_url": repo_url,
        "repo_name": repo_name,
        "push_status": "success (force-pushed to existing)",
    })
